export default [
    {
        titleAr:"اجتماعية",
        titleEn:"Social",
        id:1
    },
    {
        titleAr:"تاريخ",
        titleEn:"History",
        id:2
    },
    {
        titleAr:"سفر",
        titleEn:"Travel",
        id:3
    },
    {
        titleAr:"أماكن",
        titleEn:"Places",
        id:4
    },
    {
        titleAr:"أجهزة",
        titleEn:"Devices",
        id:5
    },
    {
        titleAr:"تقنية",
        titleEn:"Tech",
        id:6
    },
    {
        titleAr:"اقتصادية",
        titleEn:"Eccomerce",
        id:7
    },
    {
        titleAr:"دينية",
        titleEn:"Religion",
        id:8
    }
]